### ISSUE TITLE
unable to install Microsoft.Security.DevOps.Policy.Names with Microsoft.Security.Devops.Cli.linux-x64 version 0.206.0

### ISSUE THREAD

**Issue by prototype7630** [microsoft/security-devops-action#95]
OS: Ubuntu 20.04 x64
previously working: yes

Running in an Azure DevOps pipeline with the Microsoft Security DevOps template, which looks as follows:

steps:
- task: MicrosoftSecurityDevOps@1
  displayName: 'Microsoft Security DevOps'
  inputs:
   categories: 'IaC'
   tools: 'terrascan'
   
  Was working fine with version 0.205.0 previously

error:

Run:
  Installing Microsoft.Security.DevOps.Policy.Names
  ------------------------------------------------------------------------------
      GET https://msdoaus.pkgs.visualstudio.com/13093195-169e-483f-9f67-816ff7b2736d/_packaging/fab91623-9140-47c7-8c02-620e184af916/nuget/v3/registrations2-semver2/microsoft.security.***ops.policy.names/index.json
      Unauthorized https://msdoaus.pkgs.visualstudio.com/13093195-169e-483f-9f67-816ff7b2736d/_packaging/fab91623-9140-47c7-8c02-620e184af916/nuget/v3/registrations2-semver2/microsoft.security.***ops.policy.names/index.json 493ms
  ------------------------------------------------------------------------------
##[warning]Failed to install from source https://ff1a9733-c11f-5cef-b87a-175efb0b64be-fedphfembug6gddt.b02.azurefd.net/nuget/v3/index.json with exception NuGet.Protocol.Core.Types.FatalProtocolException: An error occurred while retrieving package metadata for 'Microsoft.Security.DevOps.Policy.Names' from source 'MSCA.Policy'.
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized - No local versions of package 'microsoft.security.***ops.policy.names'; please provide authentication to access versions from upstream that have not yet been saved to your feed. (DevOps Activity ID: AF636732-5DEE-4C15-AF96-C5A1CDE46232)).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at NuGet.Protocol.HttpSource.<>c__DisplayClass15_0`1.<<GetAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func`2 action, CancellationToken token)
   at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func`2 action, CancellationToken token)
   at NuGet.Protocol.HttpSource.GetAsync[T](HttpSourceCachedRequest request, Func`2 processAsync, ILogger log, CancellationToken token)
   at NuGet.Protocol.RegistrationUtility.LoadRanges(HttpSource httpSource, Uri registrationUri, String packageId, VersionRange range, SourceCacheContext cacheContext, ILogger log, CancellationToken token)
   at NuGet.Protocol.ResolverMetadataClient.GetDependencies(HttpSource httpClient, Uri registrationUri, String packageId, VersionRange range, SourceCacheContext cacheContext, ILogger log, CancellationToken token)
   at NuGet.Protocol.ResolverMetadataClient.GetRegistrationInfo(HttpSource httpClient, Uri registrationUri, String packageId, VersionRange range, SourceCacheContext cacheContext, NuGetFramework projectTargetFramework, ILogger log, CancellationToken token)
   at NuGet.Protocol.DependencyInfoResourceV3.ResolvePackages(String packageId, NuGetFramework projectFramework, SourceCacheContext cacheContext, ILogger log, CancellationToken token)
   --- End of inner exception stack trace ---
   at NuGet.Protocol.DependencyInfoResourceV3.ResolvePackages(String packageId, NuGetFramework projectFramework, SourceCacheContext cacheContext, ILogger log, CancellationToken token)
   at NuGet.PackageManagement.NuGetPackageManager.GetLatestVersionCoreAsync(String packageId, NuGetVersion version, NuGetFramework framework, ResolutionContext resolutionContext, SourceRepository source, ILogger log, CancellationToken token)
   at NuGet.PackageManagement.NuGetPackageManager.<>c__DisplayClass106_1.<<GetLatestVersionAsync>b__3>d.MoveNext()
--- End of stack trace from previous location ---
   at NuGet.PackageManagement.NuGetPackageManager.GetLatestVersionAsync(String packageId, NuGetFramework framework, ResolutionContext resolutionContext, IEnumerable`1 sources, ILogger log, CancellationToken token)
   at NuGet.PackageManagement.NuGetPackageManager.GetLatestVersionAsync(String packageId, NuGetProject project, ResolutionContext resolutionContext, IEnumerable`1 sources, ILogger log, CancellationToken token)
   at Microsoft.Guardian.Installers.NuGetSdkClient.Install(PackageConfig packageConfig, String outputDirectory)
##[error]PackageInstallerException: Failed to install NuGet package: Microsoft.Security.DevOps.Policy.Names vundefined
##[error]MSDO CLI exited with an error exit code: 1

**Comment by prototype7630** [comment]
nm, looks like it's sorted now
